"""
utils/env_manager.py — .env file read/write helpers for project directories.

All values are stored in the project's .env file. Uploaded files are
validated for size before being saved.
"""
import logging
from pathlib import Path
from typing import Dict, Tuple

logger = logging.getLogger(__name__)

MAX_ENV_FILE_BYTES = 50 * 1024  # 50 KB hard limit on uploaded .env files
MAX_ENV_VARS = 100               # Maximum number of variables allowed


def load_env_file(project_dir: Path) -> Dict[str, str]:
    """
    Parse KEY=VALUE pairs from the project .env file.

    Args:
        project_dir: Root directory of the project.

    Returns:
        Dict of variable names to values (empty if file absent).
    """
    env_file = project_dir / ".env"
    env_vars: Dict[str, str] = {}
    if not env_file.exists():
        return env_vars
    try:
        with open(env_file, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env_vars[key.strip()] = value.strip()
    except Exception as exc:
        logger.warning("Error loading .env from %s: %s", project_dir, exc)
    return env_vars


def save_env_file(project_dir: Path, env_vars: Dict[str, str]) -> bool:
    """
    Write KEY=VALUE pairs back to the project .env file.

    Args:
        project_dir: Root directory of the project.
        env_vars: Mapping of variable names to values.

    Returns:
        True on success, False on error.
    """
    env_file = project_dir / ".env"
    try:
        with open(env_file, "w", encoding="utf-8") as fh:
            fh.write("# Environment Variables\n# Auto-generated by HostingBot\n\n")
            for key, value in sorted(env_vars.items()):
                fh.write(f"{key}={value}\n")
        return True
    except Exception as exc:
        logger.error("Error saving .env to %s: %s", project_dir, exc)
        return False


def set_env_var(project_dir: Path, key: str, value: str) -> Tuple[bool, str]:
    """
    Add or update a single environment variable.

    Args:
        project_dir: Project root.
        key: Variable name (alphanumeric + underscore only).
        value: Variable value.

    Returns:
        (success, message) tuple.
    """
    if not key or not key.replace("_", "").isalnum():
        return False, "❌ Invalid key name. Use letters, digits, and underscores only."

    env_vars = load_env_file(project_dir)

    if len(env_vars) >= MAX_ENV_VARS and key.upper() not in env_vars:
        return False, f"❌ Maximum of {MAX_ENV_VARS} variables reached."

    env_vars[key.upper()] = value
    if save_env_file(project_dir, env_vars):
        return True, f"✅ Variable <code>{key.upper()}</code> set successfully."
    return False, "❌ Failed to save environment variable."


def delete_env_var(project_dir: Path, key: str) -> Tuple[bool, str]:
    """
    Remove a variable from the .env file.

    Args:
        project_dir: Project root.
        key: Variable name to delete.

    Returns:
        (success, message) tuple.
    """
    env_vars = load_env_file(project_dir)
    if key.upper() not in env_vars:
        return False, f"❌ Variable <code>{key.upper()}</code> not found."
    del env_vars[key.upper()]
    if save_env_file(project_dir, env_vars):
        return True, f"✅ Variable <code>{key.upper()}</code> deleted."
    return False, "❌ Failed to delete environment variable."


def get_env_display(project_dir: Path) -> str:
    """
    Return a masked summary of all environment variables.

    Values are partially masked so secrets aren't fully exposed in chat.

    Args:
        project_dir: Project root.

    Returns:
        Formatted HTML string.
    """
    env_vars = load_env_file(project_dir)
    if not env_vars:
        return "📝 No environment variables set."

    lines = ["🔐 <b>Environment Variables:</b>\n"]
    for key, value in sorted(env_vars.items()):
        if len(value) > 8:
            masked = f"{value[:3]}...{value[-2:]}"
        elif len(value) > 3:
            masked = f"{value[0]}***"
        else:
            masked = "***"
        lines.append(f"├─ <code>{key}</code> = {masked}")
    return "\n".join(lines)


def save_uploaded_env_file(project_dir: Path, content: bytes) -> Tuple[bool, str]:
    """
    Validate and save an uploaded .env file.

    Args:
        project_dir: Project root.
        content: Raw bytes from the uploaded file.

    Returns:
        (success, message) tuple.
    """
    if len(content) > MAX_ENV_FILE_BYTES:
        return False, f"❌ File too large. Maximum allowed size is {MAX_ENV_FILE_BYTES // 1024} KB."

    env_file = project_dir / ".env"
    try:
        env_file.write_bytes(content)
        parsed = load_env_file(project_dir)
        if len(parsed) > MAX_ENV_VARS:
            env_file.unlink(missing_ok=True)
            return False, f"❌ File contains more than {MAX_ENV_VARS} variables."
        return True, f"✅ .env uploaded successfully ({len(parsed)} variables loaded)."
    except Exception as exc:
        logger.error("Error saving uploaded .env: %s", exc)
        return False, f"❌ Error saving file: {exc}"
